[package]
name = "isa-mos6502"
version = "2.0.0"
authors = ["Nate Catelli <ncatelli@packetfire.org>"]
edition = "2021"

[dependencies]
parcel = { git = "https://github.com/ncatelli/parcel", tag = "v2.0.1" }
