[package]
name = "isa-mos6502"
version = "1.0.1"
authors = ["Nate Catelli <ncatelli@packetfire.org>"]
edition = "2018"

[dependencies]
parcel = { git = "https://github.com/ncatelli/parcel", tag = "v2.0.1" }
